sudo: false
services:
  - docker

script:
  - docker-compose up
  - docker-compose run web gem install bundler
  - docker-compose run web bundle install
  - docker-compose run web bundle exec rake ci
